server:
  port: 8002
spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.0.180:3306/db2019?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiaoke.springcloud.entities